### ISSUE TITLE
There is no User Login system or personal playlist option

### ISSUE THREAD

**Issue by pavanamballa** [abh1jith/playlist-holder#2]
The website (when hosted) does not seem to have user authentication, or any form of personal playlist option. Anyone with the access to the link from anywhere can add or delete any songs.

**Comment by pavanamballa** [comment]
I have worked on this issue and created a Pull Request for the original owner to verify. Please clear this issue once it has been verified!

**Comment by abh1jith** [comment]
I just went through your code files, and this issue has been sorted. Thank you for working on this project!
